name: nexus_news
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  iconsax: ^0.0.8
  cached_network_image: ^3.4.1
  another_carousel_pro: ^1.0.2
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  readmore: ^3.0.0
  intl: ^0.19.0
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/nexus-logo.png
    - assets/images/avatar.jpg
    - assets/images/Authentication.png

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf

    - family: Semibold
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
  
    - family: Medium
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
  
    - family: Regular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
  
    - family: Light
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
