name: nexus_news
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/OIG1.vz6y5D-removebg-preview.png

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf

    - family: Semibold
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
  
    - family: Medium
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
  
    - family: Regular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
  
    - family: Light
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
